---

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: "Copy config file"
  fetch:
    src: "{{ kubeadmin_config }}"
    dest: "{{ lookup('env', 'HOME') }}/admin.conf"
    flat: yes
  run_once: yes
  ignore_errors: yes

- name: Download admin.conf to {{playbook_dir}}/.secret/{{ kubeadmin_config | basename}}  to populate it to nodes
  #when: init_cluster is succeeded
  fetch:
    src: "{{ kubeadmin_config }}"
    dest: "{{playbook_dir}}/.secret/{{ kubeadmin_config | basename}}"
    flat: true
